#!/bin/bash

# Script to run SEDNet inference with confidence filtering
# Based on the paths defined in process_stereo_foundation.sh

# =============================================
# Configuration
# =============================================

BASE_DIR="/mnt/h/RGBD-500"
SEDNET_DIR="/mnt/h/SEDNet"

# Input paths (rotated stereo images from process_stereo_foundation.sh)
LEFT_ROTATED_DIR="${BASE_DIR}/stereo/left_rotated"
RIGHT_ROTATED_DIR="${BASE_DIR}/stereo/right_rotated"

# Camera intrinsics file (generated by process_stereo_foundation.sh)
INTRINSIC_FILE="${BASE_DIR}/K.txt"
TRANSFORMS_JSON="${BASE_DIR}/transforms.json"

# Output directory
OUTPUT_DIR="${BASE_DIR}/stereo"

# Model parameters
MODEL="gwcnet-gcs"  # GwcNet with uncertainty estimation
SCENEFLOW_CHECKPOINT="/mnt/h/SEDNet/checkpoints/sceneflow/gwcnet-gc-elu-dropout-l1-logs-kl-3std-logspace-11bins-lr1e-3/checkpoint_000015.ckpt"  # UPDATE THIS PATH
MAXDISP=192
MAX_DEPTH=60.0

# Processing parameters
CONFIDENCE_THRESHOLD=0.5  # Keep pixels with lowest uncertainty (0.1 = best 10%)
SHIFT_DIRECTION="x"  # Same as used in process_stereo_foundation.sh

# =============================================
# Parse command line arguments
# =============================================
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --checkpoint)
            SCENEFLOW_CHECKPOINT="$2"
            shift 2
            ;;
        --confidence)
            CONFIDENCE_THRESHOLD="$2"
            shift 2
            ;;
        --shift-direction)
            SHIFT_DIRECTION="$2"
            shift 2
            ;;
        --max-depth)
            MAX_DEPTH="$2"
            shift 2
            ;;
        --maxdisp)
            MAXDISP="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --checkpoint PATH        Path to SceneFlow checkpoint (required)"
            echo "  --confidence FLOAT       Uncertainty percentile threshold 0.0-1.0 (default: 0.1)"
            echo "                          Keep pixels with lowest uncertainty. E.g., 0.1 = best 10%"
            echo "  --shift-direction DIR    Shift direction: x, -x, y, -y (default: x)"
            echo "  --max-depth FLOAT        Maximum depth in meters (default: 60.0)"
            echo "  --maxdisp INT            Maximum disparity (default: 192)"
            echo "  -h, --help               Show this help message"
            echo ""
            echo "Example:"
            echo "  $0 --checkpoint /path/to/sceneflow.pth --confidence 0.1  # Keep best 10%"
            echo "  $0 --confidence 0.2  # Keep best 20%"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

# =============================================
# Validate inputs
# =============================================

if [ ! -d "$LEFT_ROTATED_DIR" ]; then
    echo "Error: Left rotated directory not found: $LEFT_ROTATED_DIR"
    echo "Please run process_stereo_foundation.sh first to generate rotated images"
    exit 1
fi

if [ ! -d "$RIGHT_ROTATED_DIR" ]; then
    echo "Error: Right rotated directory not found: $RIGHT_ROTATED_DIR"
    echo "Please run process_stereo_foundation.sh first to generate rotated images"
    exit 1
fi

if [ ! -f "$INTRINSIC_FILE" ]; then
    echo "Error: Intrinsic file not found: $INTRINSIC_FILE"
    echo "Please run process_stereo_foundation.sh first to generate K.txt"
    exit 1
fi

if [ ! -f "$SCENEFLOW_CHECKPOINT" ]; then
    echo "Error: SceneFlow checkpoint not found: $SCENEFLOW_CHECKPOINT"
    echo "Please provide a valid checkpoint path using --checkpoint"
    exit 1
fi

# =============================================
# Display configuration
# =============================================

echo "========================================"
echo "SEDNet Inference with Confidence Filtering"
echo "========================================"
echo "Input directories:"
echo "  Left (rotated):  $LEFT_ROTATED_DIR"
echo "  Right (rotated): $RIGHT_ROTATED_DIR"
echo ""
echo "Camera intrinsics: $INTRINSIC_FILE"
echo "Model checkpoint:  $SCENEFLOW_CHECKPOINT"
echo ""
echo "Parameters:"
echo "  Model:               $MODEL"
echo "  Max disparity:       $MAXDISP"
echo "  Max depth:           $MAX_DEPTH m"
echo "  Confidence threshold: $CONFIDENCE_THRESHOLD"
echo "  Shift direction:     $SHIFT_DIRECTION"
echo ""
echo "Output directory: $OUTPUT_DIR"
echo "========================================"
echo ""

# =============================================
# Activate environment and run inference
# =============================================

# Activate nerfstudio environment (already has required packages)
echo "Activating nerfstudio environment..."
eval "$(conda shell.bash hook)"
conda activate nerfstudio

# Run inference
echo "Running SEDNet inference..."
cd "$SEDNET_DIR"

python inference_with_confidence.py \
    --model "$MODEL" \
    --checkpoint "$SCENEFLOW_CHECKPOINT" \
    --maxdisp "$MAXDISP" \
    --max_depth "$MAX_DEPTH" \
    --left_dir "$LEFT_ROTATED_DIR" \
    --right_dir "$RIGHT_ROTATED_DIR" \
    --intrinsic_file "$INTRINSIC_FILE" \
    --output_dir "$OUTPUT_DIR" \
    --transforms_json "$TRANSFORMS_JSON" \
    --confidence_threshold "$CONFIDENCE_THRESHOLD" \
    --shift_direction "$SHIFT_DIRECTION" \
    --save_visualization

EXIT_CODE=$?

# Deactivate environment
conda deactivate

# =============================================
# Check results
# =============================================

if [ $EXIT_CODE -eq 0 ]; then
    echo ""
    echo "========================================"
    echo "Inference completed successfully!"
    echo "========================================"
    echo "Results saved to:"
    echo "  Depth maps:      ${OUTPUT_DIR}/depth_defomstereo/"
    echo "  Confidence maps: ${OUTPUT_DIR}/confidence/"
    echo "  Disparity maps:  ${OUTPUT_DIR}/disparity/"
    echo ""
    echo "Note: Depth maps have been:"
    echo "  1. Filtered by confidence threshold: $CONFIDENCE_THRESHOLD"
    echo "  2. Unrotated back to original orientation"
    echo "  3. Ready for use with nerfstudio"
else
    echo ""
    echo "Error: Inference failed with exit code $EXIT_CODE"
    exit $EXIT_CODE
fi
